export const ERROR_MESSAGES = {
    INSUFFICIENT_BALANCE: 'SALDO INSUFICIENTE PARA COMPRAR OS TOKENS.',
    UNAVAILABLE_QUANTITY: 'QUANTIDADE DE TOKENS INDISPONÍVEL PARA COMPRA.',
    INVALID_INPUT: 'ENTRADA INVÁLIDA.',
    INVALID_VALUE: 'VALOR INVÁLIDO. DIGITE UM NÚMERO POSITIVO.',
    INVALID_QUANTITY: 'QUANTIDADE INVÁLIDA. A QUANTIDADE DEVE SER UM NÚMERO INTEIRO POSITIVO.',
    INVALID_OPTION: 'OPÇÃO INVÁLIDA. TENTE NOVAMENTE.',
    ERROR_PROCESSING_PURCHASE: 'ERRO AO PROCESSAR A COMPRA:',
    ERROR_GETTING_USER_INFO: 'ERRO AO OBTER INFORMAÇÕES DO USUÁRIO:',
  };
  