import chalk from 'chalk';

export const ERROR_MESSAGES = {
  INSUFFICIENT_BALANCE: chalk.red('SALDO INSUFICIENTE PARA COMPRAR OS TOKENS.'),
  UNAVAILABLE_QUANTITY: chalk.red('QUANTIDADE DE TOKENS INDISPONÍVEL PARA COMPRA.'),
  INVALID_INPUT: chalk.red('ENTRADA INVÁLIDA.'),
  INVALID_VALUE: chalk.red('VALOR INVÁLIDO. DIGITE UM NÚMERO POSITIVO.'),
  INVALID_QUANTITY: chalk.red('QUANTIDADE INVÁLIDA. A QUANTIDADE DEVE SER UM NÚMERO INTEIRO POSITIVO.'),
  INVALID_OPTION: chalk.red('OPÇÃO INVÁLIDA. TENTE NOVAMENTE.'),
  ERROR_PROCESSING_PURCHASE: chalk.red('ERRO AO PROCESSAR A COMPRA:'),
  ERROR_GETTING_USER_INFO: chalk.red('ERRO AO OBTER INFORMAÇÕES DO USUÁRIO:'),
};
